version: "3"
services:
  app:
    container_name: equso-app
    build: .
    ports:
    - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres
    container_name: equso-postgres
    restart: "no"
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env