logging:
  level:
    org.hibernate.type: trace

server:
  port: 8081

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: "Baovk7Gxr8YpVvrS9SKD"