spring:
  application:
    name: equso

  liquibase:
    change-log: classpath:liquibase/changelog-master.yaml

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: false


logging:
  level:
    com.uniso.equso: debug

jwt:
  secret: ${JWT_SECRET}

url:
  root: /api/v1/