spring:
  application:
    name: equso

  liquibase:
    change-log: classpath:liquibase/changelog-master.yaml

  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

  jpa:
    generate-ddl: false


logging:
  level:
    com.uniso.equso: debug

jwt:
  secret: ${JWT_SECRET}

url:
  root: /api/v1/

mybatis:
  mapper-locations: mapper/*.xml

api:
  info:
    title: Equso api documentation
    description: This api documentation used as a equso backend